const pate = require("./pate");

module.exports = {
  Ping: require("./ping"),
  Jeme: require("./jeme"),
  Uwu: require("./uwu"),
  Owo: require("./owo"),
  Foxel: require("./foxel"),
  Help: require("./help"),
  Coinflip: require("./coinflip"),
  Dice: require("./dice"),
  Lenny: require("./lenny"),
  Botinfo: require("./botinfo"),
  Serverinfo: require("./serverinfo"),
  Invite: require("./invite"),
  Fox: require("./fox"),
  Userinfo: require("./userinfo"),
  Random: require("./random"),
  Color: require("./color"),
  Reverse: require("./reverse"),
  Waifu: require("./waifu"),
  Neko: require("./neko"),
  Hentai: require("./hentai"),
  Tp: require("./tp"),
  Sus: require("./sus"),
  Avatar: require("./avatar"),
  Price: require("./price"),
  InviteCrypto: require("./invitecrypto"),
  Weather: require("./weather"),
  Wc: require("./wc"),
  Join: require("./join"),
  Leave: require("./leave"),
  Pate: require("./pate"),
  Jenna: require("./jenna"),
  Skruiba: require("./skruiba"),
  Tuukka: require("./tuukka"),
  Miksu: require("./miksu"),
  Rosa: require("./rosa"),
  Roosa: require("./roosa"),
};
