module.exports = {
  Ping: require("./ping"),
  Jeme: require("./jeme"),
  Uwu: require("./uwu"),
  Owo: require("./owo"),
  Foxel: require("./foxel"),
  Help: require("./help"),
  Coinflip: require("./coinflip"),
  Dice: require("./dice"),
  Lenny: require("./lenny"),
  Botinfo: require("./botinfo"),
  Serverinfo: require("./serverinfo"),
  Invite: require("./invite"),
  Fox: require("./fox"),
  Userinfo: require("./userinfo"),
  Random: require("./random"),
  Color: require("./color"),
};
